#!/bin/sh

REPO_URL="https://raw.githubusercontent.com/sorinpohontu/Postfix-Checks/master"
BODY_CHECKS="/etc/postfix/body_checks"
HEADER_CHECKS="/etc/postfix/header_checks"

# BODY_CHECKS
/usr/bin/wget -q --no-cache -O $BODY_CHECKS $REPO_URL$BODY_CHECKS
if [ "$?" -ne "0" ]; then
    echo "$REPO_URL$BODY_CHECKS not found ..."
else
    if [ -e $BODY_CHECKS ]; then
        /usr/sbin/postmap $BODY_CHECKS
    fi
fi

# HEADER_CHECKS
/usr/bin/wget -q --no-cache -O $HEADER_CHECKS $REPO_URL$HEADER_CHECKS
if [ "$?" -ne "0" ]; then
    echo "$REPO_URL$HEADER_CHECKS not found ..."
else
    if [ -e $HEADER_CHECKS ]; then
        /usr/sbin/postmap $HEADER_CHECKS
    fi
fi

# Restart Potfix
/usr/sbin/service postfix restart
