#!/bin/sh

REPO_URL="https://github.com/sorinpohontu/Postfix-Checks/raw/master"
BODY_CHECKS="/etc/postfix/body_checks"
HEADER_CHECKS="/etc/postfix/header_checks"

# Update BODY_CHECKS
/usr/bin/wget -q -O $BODY_CHECKS $REPO_URL$BODY_CHECKS
if [ "$?" -ne "0" ]; then
    echo "$REPO_URL$BODY_CHECKS not found ..."
else
    if [[ -e $BODY_CHECKS ]]; then
        echo "Postmapping $BODY_CHECKS ..."
        /usr/sbin/postmap $BODY_CHECKS
    fi
fi

# Update HEADER_CHECKS
/usr/bin/wget -q -O $HEADER_CHECKS $REPO_URL$HEADER_CHECKS
if [ "$?" -ne "0" ]; then
    echo "$REPO_URL$HEADER_CHECKS not found ..."
else
    if [[ -e $HEADER_CHECKS ]]; then
        echo "Postmapping $HEADER_CHECKS ..."
        /usr/sbin/postmap $HEADER_CHECKS
    fi
fi

# Restart Potfix
/usr/sbin/service postfix restart
